FROM golang:1.19-alpine3.16 AS build

RUN apk update && apk add alpine-sdk git ca-certificates && rm -rf /var/cache/apk/*
ADD ./ /var/app
WORKDIR /var/app
RUN go mod download -x
RUN GOOS=linux CGO_ENABLED=1 go build -o main .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=build /var/app/ip_white_list ./
COPY --from=build /var/app/main ./
CMD ["./main"]
