FROM golang:1.19 AS build
WORKDIR /go/src/github.com/85yago/go_small_chat/app
COPY . .
RUN go mod download -x
RUN GOOS=linux CGO_ENABLED=1 go build -o main . -tags=release

FROM golang:1.19-alpine3.16 AS development
RUN apk --no-cache add alpine-sdk ca-certificates gcc git

FROM alpine:3.16
RUN apk --no-cache add ca-certificates
EXPOSE 443
COPY --from=build /go/src/github.com/85yago/go_small_chat/app/ip_white_list ./
COPY --from=build /go/src/github.com/85yago/go_small_chat/app/main ./
CMD ["./main"]
